set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-257color"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r Tab last-window

bind -r D neww -c "#{pane_current_path}" 'if [ -e TODO.md ]; then nvim TODO.md; else nvim ~/todo/todo.md; fi'
bind -r G neww -c "#{pane_current_path}" 'if [ -e DS.md ]; then nvim DS.md; else nvim ~/ds.md fi'

bind-key -r f run-shell "~/.local/bin/tmux-sessionizer"
bind-key -r C run-shell "~/.local/bin/tmux-sessionizer ~/Projects/code_partner"
bind-key -r M run-shell "~/.local/bin/tmux-sessionizer ~/Projects/mindora-backend"
bind-key -r N run-shell "~/.local/bin/tmux-sessionizer ~/.config/nvim/"
bind-key -r S run-shell "~/.local/bin/tmux-sessionizer ~/Projects/saleor/"
bind-key -r H run-shell "~/.local/bin/tmux-sessionizer ~/Projects/saylessai/"
